### ISSUE TITLE
可否在配置文件添加可选择关闭AI

### ISSUE THREAD

**Issue by ABKQPO** [canxin121/Spark-GPT#12]

**Comment by canxin121** [comment]
你不填相应配置就关了，有不会的建议先加群问，这些都是本来就有的......

**Comment by ABKQPO** [comment]
给一下群号谢谢

**Comment by canxin121** [comment]
用户交流群:[610948446](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=KHGqjjbiz6fpRr-W2X9SugTXThKFiprJ&authKey=LhpClaGtc4%2Ff3EL7f4IIIt7F94vLHJj4HSS8c2YCE55nRBRBtftzla%2Bgj7pa0fWX&noverify=0&group_code=610948446)
