### ISSUE TITLE
讯飞星火抓不到包

### ISSUE THREAD

**Issue by Laurc2004** [canxin121/Spark-GPT#13]
![image](https://github.com/canxin121/Spark-GPT/assets/119660750/0cb02eed-d06c-4ee6-bc3f-e7061c413882)
没有信息 我打开方式不对吗

**Comment by araea** [comment]
不用抓包，直接Chrome开发者模式网络里监视。

**Comment by Laurc2004** [comment]
> Reference in new issue
> 
> ### Reference in new issue

不行的，调不出开发者模式

**Comment by canxin121** [comment]
![image](https://github.com/canxin121/Spark-GPT/assets/69547456/d7a3f003-69cb-42ca-bc30-876a69acb605)
![image](https://github.com/canxin121/Spark-GPT/assets/69547456/c4bfedf9-81df-43cc-a875-749002407ea4)

**Comment by Laurc2004** [comment]
![image](https://github.com/canxin121/Spark-GPT/assets/119660750/83383585-8346-4311-8b8b-f9d73cb38f59)
为什么还是抓不到 麻烦您给看看 是哪里出问题了

**Comment by araea** [comment]
> ![image](https://user-images.githubusercontent.com/119660750/240456467-83383585-8346-4311-8b8b-f9d73cb38f59.png) 为什么还是抓不到 麻烦您给看看 是哪里出问题了

建议加群 来聊聊天 这里发效率不高
