### ISSUE TITLE
自动创建gpt3.5失败，多次失败请联系机器人管理员

### ISSUE THREAD

**Issue by yangdffdzvzvr** [canxin121/Spark-GPT#15]
poe,谷歌账户登录，一直提示 自动创建gpt3.5失败，多次失败请联系机器人管理员
![@FZFQ%@)CN1@LU@73$(5 RN](https://github.com/canxin121/Spark-GPT/assets/118903437/0b895486-2fff-4563-9cbe-5816402accb5)

**Comment by canxin121** [comment]
获取ck时请确保可以创建bot，先创建一个bot试一下https://canxin121.github.io/docs/docs/Spark_GPT.html#poe%E9%85%8D%E7%BD%AE

**Comment by yangdffdzvzvr** [comment]
poe官网是可以创建bot的，当使用pc指令创建bot时，poe官网也出现了新的bot，但群里还是回复自动创建gpt3.5失败，多次失败请联系机器人管理员
