### ISSUE TITLE
目前好像不可以创建Claude Slack、Spark Desk、通义千问

### ISSUE THREAD

**Issue by cj1357** [canxin121/Spark-GPT#22]
目前6项中没有Claude Slack、Spark Desk、通义千问，但是webui里面却可以配置它们
![image](https://github.com/canxin121/Spark-GPT/assets/40661342/6005c9ab-6300-41c9-b71f-fa1fb3ce324e)
![image](https://github.com/canxin121/Spark-GPT/assets/40661342/8a97b41d-a1e1-4c98-b189-e3ba9e95ad56)

**Comment by canxin121** [comment]
配置完才可以使用，填写相关的cookie等字段，就可以使用了。
