### ISSUE TITLE
Bard模型给bot取中文名导致回复总是为提示不支持的语言

### ISSUE THREAD

**Issue by cj1357** [canxin121/Spark-GPT#23]
这是把bot的名字也一起作为提问了么
![image](https://github.com/canxin121/Spark-GPT/assets/40661342/1f7d4102-1283-48a2-ad67-3dcb94896e0b)

改成英文名的bot就能正确回答
![image](https://github.com/canxin121/Spark-GPT/assets/40661342/0a6c8f82-20c7-494a-a15e-c73db29448b9)

**Comment by canxin121** [comment]
应该并不会把名字发过去的，可以再试试，我这里没有出现过这种情况。询问的问题和获取chatbot的处理，所有来源都是统一的，应该不会单独某个来源把问题的bot名没删掉

**Comment by canxin121** [comment]
![Uploading F37599FD-8DA6-480D-B4CF-A34611CCEBD2.png…]()

**Comment by cj1357** [comment]
知道问题了，bard第一次的时候好像都会提示还在学习这项语言，之后再提问就好了
![image](https://github.com/canxin121/Spark-GPT/assets/40661342/f0989b8c-56fd-4699-8567-8965dbaf7d0c)
![image](https://github.com/canxin121/Spark-GPT/assets/40661342/1a08cd20-0a88-4ea3-bd38-318c26e65476)

**Comment by cj1357** [comment]
它真的提取到了这个名字，还认为这是我的名字？
![image](https://github.com/canxin121/Spark-GPT/assets/40661342/863a0d75-0c8d-4a6e-aaae-e6b3f5441e8a)

**Comment by cj1357** [comment]
没事了，现在bard支持中文了，无所谓了2333
