### ISSUE TITLE
最好修改spark_port

### ISSUE THREAD

**Issue by mcwindy** [canxin121/Spark-GPT#24]
chrome默认限制6666端口，最好将readme中的端口修改为其他端口如7777
https://www.cnblogs.com/huanxiyun/p/5407932.html

**Comment by canxin121** [comment]
默认端口为8666.应该没有冲突吧

**Comment by canxin121** [comment]
哦哦，知道了，我readme写错了，瞎了0.0

**Comment by canxin121** [comment]
已更正文档
