### ISSUE TITLE
希望增加不显示正在思考以及撤回此消息的选项配置

### ISSUE THREAD

**Issue by mcwindy** [canxin121/Spark-GPT#25]

**Comment by kureinaikai** [comment]
去\.venv\Lib\site-packages\nonebot_plugin_spark_gpt\platforms\nonebot\bot_main.py
把reply_msgs.append(await reply_message(bot, matcher, event, "正在思考，请稍等"))
和
try:
        await delete_messages(bot, event, reply_msgs)
    except:
        # logger.error("撤回消息失败")
        pass
注释掉就好了

**Comment by canxin121** [comment]
奇怪的需求，但是满足你吧，今天更新这个的webui配置项

**Comment by canxin121** [comment]
已更新1.1.2
