### ISSUE TITLE
图片错误

### ISSUE THREAD

**Issue by yangdffdzvzvr** [canxin121/Spark-GPT#27]
wkhtmltopdf安装好了，环境变量也配置了，重启过，发送的图片还是错误
![QQ图片20230715202121](https://github.com/canxin121/Spark-GPT/assets/118903437/835a0e84-430b-4d87-b58f-52815b99390f)
![QQ图片20230715202253](https://github.com/canxin121/Spark-GPT/assets/118903437/d44a9b2f-c56c-4415-a5d5-e6e38bf234ba)

**Comment by canxin121** [comment]
刚刚推了一个playwright版本的,你可以更新试试,1.1.7

**Comment by yangdffdzvzvr** [comment]
> 刚刚推了一个playwright版本的,你可以更新试试,1.1.7

好了，1.1.7正常了

**Comment by yangdffdzvzvr** [comment]
> 刚刚推了一个playwright版本的,你可以更新试试,1.1.7

大佬大佬，这个回复功能是不是不可用？试了没反应
![QQ图片20230715212113](https://github.com/canxin121/Spark-GPT/assets/118903437/7bf488f7-50e9-4e5b-9933-d2b06677f92a)

**Comment by canxin121** [comment]
> > 刚刚推了一个playwright版本的,你可以更新试试,1.1.7
> 
> 大佬大佬，这个回复功能是不是不可用？试了没反应 ![QQ图片20230715212113](https://user-images.githubusercontent.com/118903437/253742003-7bf488f7-50e9-4e5b-9933-d2b06677f92a.png)

只能回复某个bot的最后一个回复,下版本我写清楚点吧,这次化简过头了

**Comment by canxin121** [comment]
<img width="1084" alt="image" src="https://github.com/canxin121/Spark-GPT/assets/69547456/063743a6-81d2-45ac-9adb-b31c8751dd21">
