### ISSUE TITLE
ChatGPT web在发送请求时出错:'error'

### ISSUE THREAD

**Issue by cj1357** [canxin121/Spark-GPT#28]
QQ提示：ChatGPT在发送请求时错误次数超过上限

代码报错：
![image](https://github.com/canxin121/Spark-GPT/assets/40661342/6330d864-3d6f-4b06-9891-fe7a42ce7627)

删掉bot重新创建也是一样报错

**Comment by cj1357** [comment]
重新填了更新后的session token并重启了bot，也是一样出错

**Comment by canxin121** [comment]
我这里也是,稍等我看看吧,可以先用poe的

**Comment by cj1357** [comment]
> 我这里也是,稍等我看看吧,可以先用poe的

OK

**Comment by canxin121** [comment]
知道了,返回数据变化了,已经适配了,待会测试没啥问题推送一个新版

**Comment by cj1357** [comment]
已经好了😺
