### ISSUE TITLE
使用poe的chatgpt时候出错

### ISSUE THREAD

**Issue by MaboroneSeika** [canxin121/Spark-GPT#30]
如图，另外在使用chatgptweb时经常出现机器人回复不全，适用Sydney时它总是回复全英文。还有可以问一下怎样设定newbing使用什么模式（创造性，平衡选项）吗？
![IH)4`HY` F1 }0F% UCP(66](https://github.com/canxin121/Spark-GPT/assets/105148205/7cb9ba75-e66d-4b6d-894b-8cea80afb9a0)
![image](https://github.com/canxin121/Spark-GPT/assets/105148205/571cc50d-8e3a-48dd-8b6b-2f98b18a3247)
![image](https://github.com/canxin121/Spark-GPT/assets/105148205/afe8bd99-8a1c-4e57-bddc-2791e6776dab)

**Comment by canxin121** [comment]
poe的话,现在逆向和网站运维正在激烈交战.然后gptweb回复不全可能是字数太长了,现在网页版api应该还没有自动续写功能,然后sdyneybing是英文的话,可能和你bing的地区语言设置有关.newbing模式切换在最新版的/shelp有写,可以更新下

**Comment by canxin121** [comment]
你可以在bing的设置切换到中文试试,其次可尝试给sdyney的预设里面写上让它说中文,或者加个前缀,"请用中文回答我下面的问题:"

**Comment by MaboroneSeika** [comment]
> 你可以在bing的设置切换到中文试试,其次可尝试给sdyney的预设里面写上让它说中文,或者加个前缀,"请用中文回答我下面的问题:"

OK,我试试，这么晚还在回复辛苦了，大佬早休息

**Comment by canxin121** [comment]
poe修复了,升级到最新版的sparkgpt
```
nb plugin update spark_gpt
```
然后在升级到最新版的async-poe-client
在虚拟环境里面执行
```
pip install async-poe-client==0.1.0
```

或者也可以等我测试稳定之后直接再更新一次spark_gpt
