### ISSUE TITLE
claude ai回复有问题

### ISSUE THREAD

**Issue by cj1357** [canxin121/Spark-GPT#32]
没有预设的回复是空
![image](https://github.com/canxin121/Spark-GPT/assets/40661342/ab4dbdd9-9c05-489a-9447-6b118ba4bdb1)

有预设的回复很奇怪
![image](https://github.com/canxin121/Spark-GPT/assets/40661342/cec95493-7dc4-4947-b1b5-852a55897a8f)

**Comment by canxin121** [comment]
修好了,claude.ai那边改了输出格式

**Comment by cj1357** [comment]
感谢大佬😺
