### ISSUE TITLE
poe官网样式更新 对话报错Failed to extract 'viewer' or 'user_id' from 'next_data'.

### ISSUE THREAD

**Issue by cj1357** [canxin121/Spark-GPT#36]
![image](https://github.com/canxin121/Spark-GPT/assets/40661342/e563a185-09d9-4879-a80e-f0ade33843a3)

**Comment by Syylt** [comment]
插眼

**Comment by canxin121** [comment]
poe 将被放弃支持,因为 免费用户每天10条的逆天次数
