### ISSUE TITLE
poe 在首次创建会话的时候会报错

### ISSUE THREAD

**Issue by qianxuu** [canxin121/Spark-GPT#41]
第一次聊天会报 Poe刷新对话时出错:'Poe_Client' object has no attribute 'send_message'
继续发消息可以恢复正常

**Comment by canxin121** [comment]
啊? 怎么可能能用? 应该已经完全炸了啊???我在重构了,包括poe的逆向库和spark gpt, 只不过也有别的事情忙, 有能力的话可以帮帮我.

**Comment by qianxuu** [comment]
> 啊? 怎么可能能用? 应该已经完全炸了啊???我在重构了,包括poe的逆向库和spark gpt, 只不过也有别的事情忙, 有能力的话可以帮帮我.

![image](https://github.com/canxin121/Spark-GPT/assets/62287903/cf122270-917a-4909-a759-e5378956cae0)
我这里能用，只有第一次会报错，不过预设没生效

**Comment by canxin121** [comment]
已经更新2.0.0
